### ISSUE TITLE
Support China-based Users

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#1101]
### Overview
Users in China are having difficulty accessing the wallet. All render.com services (frontend, contract-helper, RPC, Explorer) are inaccessible. Users over VPN are struggling to receive SMS messages.

### TODOs
- [ ] Switch main wallet to use Netlify (accessible in China)
- [ ] Have contract helper proxy endpoint for China (and use it automatically when needed)
- [ ] Make sure RPC also either accessible directly or has proxy endpoint for China
- [ ] Disable SMS (in future maybe do WeChat or whatever makes more sense in China)
- [ ] Automatically detect language and switch to Chinese

**Comment by vgrichina** [comment]
@kcole16 seems like according to @ilblackdragon wallet is completely accessible in China now at main URL.

My understanding is that Render uses Google Cloud for everything except static websites, and so is similarly available (same as our RPC).

**Comment by vgrichina** [comment]
We still need to improve localization / Disable SMS potentially

**Comment by ilblackdragon** [comment]
Is there an issue tracking wallet selection process? There is a fork version of the wallet with Chinese localization already and but apps and other links send to current wallet.

**Comment by ilblackdragon** [comment]
Just to update here, wallet does work in China but on some networks very slow still - home page sometimes loads for 20-40 seconds.

How about switching to a Cloudflare or some other CDN that is serving data from the edge?

**Comment by think-in-universe** [comment]
In my test from Zhejiang, China, the wallet page is accessible from desktop (<5s), but quite slow (>30s) when opening in mobile browser (Chrome on iPhone). I'll collect more performance data tomorrow and share here. 

I agree with @ilblackdragon that we may try with Cloudflare if possible.

**Comment by think-in-universe** [comment]
@stefanopepe the current issue of web wallet in China is that it sometimes takes users 10~60s to open the web wallet for users and make the UX horrible sometimes for not only wallet but also DApps built with NEAR.

Below are some experiments about how to improve web wallet's UX in China.



### Performacne Benchmarks


1. Here we mainly use **ping.cn** to evaluate the connection speed of the web wallet in China. e.g. https://www.ping.cn/http/wallet.near.org ;
2. User feedbacks: here we collect the feedback from users who experienced from really slow UX in most of the time;
3. Mxpenal data of the wallet if we have any performance data that can measure the loading speed of wallet, or bounce rate after visiting wallet.  


### Deployment Options

Now the wallet is deployed with Render (https://render.com), which seems performs poor in China. 

Here we're experimenting with several static site deployment solutions to compare the deployment options for web wallet. 


#### Experiment 1: Render + Cloudflare

Render supports DSN-only mode with Cloudflare and Cloudflare's CDN won't work. 

- Example: https://wallet.near.systems/ (or https://near-wallet-n8jd.onrender.com/)
- Test: https://www.ping.cn/http/wallet.near.systems

#### Experiment 2: Netlify + Cloudflare

- Example: http://wallet4.near.systems (didn't use HTTPS since some confiugration issues of Netlify when working with Cloudflare, but should be fixable)
- Test: https://www.ping.cn/http/wallet4.near.systems


#### Experiment 3: Cloudflare Pages

- Example: https://wallet3.near.systems
- Test: https://www.ping.cn/http/wallet3.near.systems


#### Experiment 4: GitHub Pages

I haven't tried since I have some negative feedback about GitHub pages's performance in China recently. 

#### Experiment 5: Use CDN in China

The solution was skipped so far due to complex configuration requirements. 


### Comparison of the Experiments

Here we provides some benchmarks of the experiments to help us to compare the define the best deployment options of our web wallet. 

The speed benchmarks here comes from some users who consistenly experienced from bad UX，though may not be an average case, but can be reproduced consistenly for those users. 

| Solution | Example | ping.cn (average) | user reported | 
| -------- | -------- | -------- | -------- |
| Render | https://wallet.testnet.near.org/ | 2.269s | 42.56s  | 
| Render + Cloudflare | https://wallet.near.systems | 1.729s | 48.1s  | 
| Netlify + Cloudflare | http://wallet4.near.systems | 1.244s | 6.43~6.97s  | 
| Cloudflare Pages | http://wallet3.near.systems | 4.201s | 5.17s~5.22s  | 


### Conclusion

1. Netlify + Cloudflare or Cloudflare Pages is a more acceptable soluiton in China
2. We may direct the wallet to different CDNs especially for China. jsDelivr is an example. 


### Reference

1. How jsDelivr works in China: https://github.com/jsdelivr/jsdelivr#china

**Comment by think-in-universe** [comment]
Things to consider:

1. Will the change impact the current CI/CD workflow of wallet? we could still use Netlify / Render for preview and testing of each PR or staging version. but please confirm whether there're other side effect. 
2. Will the loading speed of wallet in other districts be impacted by the change? the Cloudflare-based solutions should perform well globally, but need more testing before putting into production.

**Comment by stefanopepe** [comment]
I see this one related to #1316 and the recent Redux optimizations by @marcinbodnar

**Comment by think-in-universe** [comment]
June 15th is the preferred time to deliver the fix to this issue. If we indeed cannot get it ready before June 15th, June 18th is the deadline, otherwise we may miss an important project in this month.

**Comment by MaximusHaximus** [comment]
@think-in-universe in order to identify exactly what we need to do / code we need to land to help with this performance issue, we need to be absolutely clear what part of the loading process is blocking users from using the UI for 40+ seconds.
If the screenshot on https://github.com/near/near-wallet/issues/1316#issuecomment-859737865 is from inside of China, and it is taking 1 second to download our JS bundle, then I would suspect that the issue isn't actually with throughput for downloading large data, but instead is centered around the # of RPC requests that are being sent during loading that the UI currently waits for to finish rendering.

Could you help get a .har log of a single full page load of the wallet from a machine inside of China that is experiencing extremely slow loading times, along with the # of seconds it took for the UI of the Wallet to be usable during _that page load_?
Creating HAR files in Chrome instructions: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

With this information we can make clear decisions about where we need to put our efforts to make the most difference in loading times.

**Comment by think-in-universe** [comment]
@MaximusHaximus in my experiments above, since redeploying the static files could resolve the page loading issue. it's probably caused by loading the JS file in this case. (I didn't change other dependent services in my experiments).

sure. let's collect more detailed profiling data from users and figure out the root cause.

**Comment by think-in-universe** [comment]
### Summary

As we discussed in Slack and Discord, JS bundle and other static assets are the bottleneck of initial page loading for wallet users in some districts like China.

Below are data collected on June 25th by Amos that confirmed the speed is still quite slow 

```
https://wallet.testnet.near.org/ (Render): 1.4 ~ 1.5m
https://wallet.near.systems/ (Render + Cloudflare): 46 ~ 47s
https://wallet3.near.systems/ (Cloudflare Pages): 3s
```

### Solutions

1. The complete fix would require us migrating the deployment onto Cloudflare Pages and Cloudflare for all the configurations including DNS / SSL / CI, etc.
2. A quick and temporary solution is to replace the link to local JS / CSS assets with resources from another host, by making  `src/index.html` hardcoded with js/css links from one Cloudflare Pages deployment such as https://wallet3.near.systems/ , e.g.  `<script src="https://wallet3.near.systems/src.4965f7fa.js"></script>` , but this will definitely break our current CI process, and is only a temporary solution. (also we need to resolve the CORS issue of loading woff2, and update how images are imported).
