### ISSUE TITLE
WAL-50 Wrap/Unwrap $NEAR

### ISSUE THREAD

**Issue by stefanopepe** [near/near-wallet#2256]
## Story

As a USER who holds wNEAR (wrapped $NEAR), I want to unwrap them with a button in the wallet dashboard, so I can make the liquid in the available balance.

As a USER who holds $NEAR (native currency of NEAR Protocol), I want to wrap them with a button in the wallet dashboard, so I can make them available as wNEAR.

## Acceptance Criteria

- [ ] The wrap/unwrap command is visible but doesn't disrupt the existing UI
- [ ] The wallet doesn't allow to wrap "too many" or "too few" $NEAR
- [ ] There's an information balloon explaining what is this function doing
- [ ] Any wNEAR balance (even if small) is visible and doesn't appear low in the tokens list (to incentivize the swap operation)
- [ ] Mobile ok
- [ ] Tested

## Unhappy Path
- Tokens are lost or locked in the process
- The interface won't capture the correct balance

**Comment by stefanopepe** [comment]
This is a _good first issue_!
If you want to contribute to NEAR Wallet, this is a good opportunity for you to join our crew.

Please make sure that you write tests before asking a merge to the master branch, see [here](https://github.com/near/near-wallet/tree/master/packages/e2e-tests) for more details.

As an experiment, we offer a 750 $near bounty for the comprehensive suite of e2e tests of this feature and the functionality merged to the master branch of the codebase =)

**Comment by stefanopepe** [comment]
@corwinharrell inlcuding you in the loop, as it may help to have a basic indication on how the UI should enable the user to swap their wNEAR for $NEAR (and vice-versa).

**Comment by corwinharrell** [comment]
Thanks for creating this @stefanopepe! Would you mind adding this to product board?

**Comment by yat011** [comment]
Hi, May I know if anyone is working on this? Could I work on this?

**Comment by yat011** [comment]
@corwinharrell  Yes, I am willing to chat with ur team.

**Comment by yat011** [comment]
After chatting with @stefanopepe,  I want to share my draft UI plan here for feedback and comments. 
The plan is as follows:
  1. Add an "wrap Near" button on the navigation bar / wallet page
  2. (new view) showing the swapping between NEAR and wNEAR  ( similar to ref finance). User can input the amount and click wrap/unwrap
  3. (new view) Review how much near being wrapped/unwrapped -> confirm button
  4. (new view) Success page

**Comment by yat011** [comment]
Hi @stefanopepe and @corwinharrell, I would like to share some updates on the UI implementation as follows. 

## Wrapping Near

1. Click Wrap NEAR.

If the user has wNEAR, wNEAR always appears after NEAR in the tokens list to incentive the wrapping operation

<img src="https://user-images.githubusercontent.com/10917273/146344986-82b4d51d-d967-4918-9bee-5d4534b42a8f.png" height="500"/>
2. Input Amount to be wrap. If the user click the swap icon, the user can input unwrap amount.

To prevent the user from wrapping "too many" NEAR, available balance does not include the NEAR reserved for transaction. It reuses the existing balance implementation.

<img src="https://user-images.githubusercontent.com/10917273/146344703-ae5d9654-d499-484c-91da-e8798933a6a4.png" height="500"/>

3.
<img src="https://user-images.githubusercontent.com/10917273/146345164-abeee4da-4e70-40bc-a260-39e115789af3.png" height="500"/>

4.
<img src="https://user-images.githubusercontent.com/10917273/146345496-161e20be-1285-4a26-8579-0575712e56ba.png" height="500"/>


## If the available NEAR balance is zero

If  the wrapped NEAR balance  > the NEAR reserved for transaction and the user still has enough NEAR for unwrapping, it shows an additional banner for unwrapping wNEAR.

<img src="https://user-images.githubusercontent.com/10917273/146345522-9085879a-804a-42f0-bb21-376a1d6ba1ed.png" height="500"/>

## TODO
-  write e2e tests 

Feel free to comment and give suggestions so that I can modify accordingly.

code: https://github.com/yat011/near-wallet/tree/wrap_near_dev

**Comment by yat011** [comment]
Hi @stefanopepe and @corwinharrell, I created a pull request #2334 .

## Update:

To avoid affecting the mobile view much, I moved the wrap Near button to navigation bar. (Feel free to comment).

![Screen Shot 2021-12-24 at 3 53 35 PM](https://user-images.githubusercontent.com/10917273/147333648-0f524b27-2ec1-422f-ba07-101305671ebb.png)


If the nav space is not enough, then it shows the nav link in the menu.

![Screen Shot 2021-12-24 at 3 54 05 PM](https://user-images.githubusercontent.com/10917273/147333666-7abad103-5f93-41a5-b25f-2e7d40181c2c.png)

**Comment by agileurbanite** [comment]
Designs by @nall-near can be found here: https://www.figma.com/file/Wcl0YlyeasgfBFxJNx7vYS/WAL-48%3A-Wrap%2FUnwrap-NEAR?node-id=2063%3A7314
