### ISSUE TITLE
Recovery Options Management

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#228]
## Story

As a user, I want to view all of my setup recovery options in one place, so I can add additional options and remove existing ones.

## Acceptance Criteria

- [x] User can view email recovery
  - [x] If enabled
    - [x] Email address
    - [x] Date enabled
    - [x] “Resend email” CTA
    - [x] “Disable” CTA
  - [x] If disabled
    - [x] “Enable”
- [x] User can view phone recovery
    - [x] If enabled
      - [x] Phone number
      - [x] Date enabled
      - [x] “Resend message” CTA
      - [x] “Disable” CTA
    - [ ] If not enabled
      - [ ] “Enable”
- [x] User can view seed phrase recovery
  - [ ] If enabled
    - [ ] Date enabled
    - [ ] “Disable” CTA
  - [ ] If not enabled
    - [ ] “Enable”
- [x] If a user tries to view a recovery setup page (`/setup-recovery`) while the option is enabled, redirect to `/profile`
- [x] Mobile ok
- [x] Tested

## Assets
[User Flows](https://docs.google.com/document/d/1AdQyVtxUTxRUhDMGrItp5AwiCa8BEnzVb2QaRLJdtxU/edit)
[Designs](https://projects.invisionapp.com/share/SKQKQ6B4PYU#/screens/359877550_Account)

**Comment by vgrichina** [comment]
I think we should replace "Full Access Keys" with some more user-focused language. E.g. "Authorized Devices" or smith like that. 

>  User must confirm intent to deauthorize

Also shouldn't be possible to remove last key without completely removing account.

> Full Access Keys do not appear in Summary

I think that it's good idea to show device that have access in summary. That way user is more likely to notice that there are some old device still in the list and can clean them up. It's likely best to highlight which devices haven't been used for signing for a while.

**Comment by kcole16** [comment]
> I think we should replace "Full Access Keys" with some more user-focused language. E.g. "Authorized Devices" or smith like that.

Agreed. I think we can show both "Recovery Options" (keys associated w/ email, seed phrase, etc) and "Authorized Devices", and avoid using the word "key" entirely.

**Comment by vgrichina** [comment]
> Agreed. I think we can show both "Recovery Options" (keys associated w/ email, seed phrase, etc) and "Authorized Devices", and avoid using the word "key" entirely.

+1.
