### ISSUE TITLE
Delegation

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-wallet#521]
### Overview
Allow users to delegate via Wallet.

### Stories
- [ ] User wants to delegate their tokens to a validator
- [ ] User wants to un-delegate their tokens from a validator
- [ ] User wants to see how much tokens was delegated and to which validators
- [ ] User wants to see how much reward accrued

**Comment by kcole16** [comment]
@ilblackdragon What is the required timeline for this? Discussed making a separate app for delegation for Stake Wars v2 w/ @jimmy3dita, then working into the Wallet.

**Comment by jimmy3dita** [comment]
Update:
- the delegation contract is under refactoring by @evgenykuzyakov 
- the delegation UI will be a separate app, using NEAR Login to connect with the wallet
- this app will be linked by Stake Wars page on the website
- the application should become one of the examples on near.dev

**Comment by kcole16** [comment]
Closing, opened #722
