### ISSUE TITLE
Setup new domain (near.org)

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#542]
### Overview
Setup new urls for wallet and near-contract-helper using near.org domain. We will keep the nearprotocol.com subdomains live as well, for the time being.

### TODOs
- [ ] Wallet
  - [x] wallet.testnet.near.org
  - [ ] wallet.near.org redirects to-> wallet.testnet.near.org
  - [x] wallet.betanet.near.org
  - [x] wallet.devnet.near.org
- [x] Helper
  - [x] helper.testnet.near.org
  - [x] helper.betanet.near.org
  - [x] helper.devnet.near.org

**Comment by kcole16** [comment]
@vgrichina Who should handle this?

**Comment by vgrichina** [comment]
Basically done at this point besides confusion around `wallet.near.org redirects to-> wallet.testnet.near.org`
