### ISSUE TITLE
Limited Access Key Support (Accounts with Contracts)

### ISSUE THREAD

**Issue by kcole16** [near/near-wallet#585]
### Overview
Users will only have limited access keys during the transfer restricted period (Mainnet Phase 0 and 1), and likely beyond (Lockup contracts and/or Multi-sig).  We currently only support Full Access Keys for transferring NEAR and signing TXs, and will need to add limited access key support prior to using the wallet on Mainnet. 

### TODOs
- [ ]  Deploy [Multi-Sig](https://github.com/near/initial-contracts/tree/master/multisig) contract to all accounts created in the Wallet via [Linkdrop](https://github.com/nearprotocol/near-linkdrop) contract
- [ ]  Differentiate between full access and limited access keys in LocalStorage
- [ ]  Handle signing with a limited access key when:
  - [ ]  Sending NEAR (/send-money)
  - [ ]  Authorizing an access key for an app (/login)
  - [ ]  Signing a TX (/sign)
  - [ ]  Removing an access key for an app
  - [ ]  Adding a new recovery method
  - [ ]  Removing a recovery method

**Comment by vgrichina** [comment]
>  Differentiate between full access and limited access keys in LocalStorage

it's available on chain, no need to differentiate in local storage per se

**Comment by bowenwang1996** [comment]
Did we calculate how much NEAR will be locked for state staking with this contract deployed?

**Comment by kcole16** [comment]
> Did we calculate how much NEAR will be locked for state staking with this contract deployed?
Not yet, but I’m not sure we have any other options to enforce transfer restriction (though we can slim down the contract I suppose).

Do you expect it might be prohibitively high?

**Comment by bowenwang1996** [comment]
No. Don't expect it to be more than 0.1 NEAR (haven't looked at the implementation but I doubt it will store a lot of data) but it's better to make sure that this isn't an issue. How much do we expect to linkdrop? Let's say we drop 1 NEAR and then 0.1 NEAR is locked. It can be a bit suboptimal.

**Comment by kcole16** [comment]
Closing in lieu of #631
