### ISSUE TITLE
Hardware Wallet Integration

### ISSUE THREAD

**Issue by eriktrautman** [near/near-wallet#62]
### Overview
To provide a high level of security, without the need for a third party custodian, we should provide support for hardware wallets (e.g. Ledger).

The user stories below are listed from highest priority to lowest.

### User Stories
- [ ] As a user, I want to create an account in the NEAR Wallet while storing my private key on a hardware wallet, so I can create a secure, self-custodied account.
- [ ] As a user, I want to open existing account(s) in NEAR Wallet that I have access key on a hardware wallet.
- [ ] As a user, I want to sign a transaction in the Wallet using my hardware wallet-secured account, so I can use apps that may not have native hardware-wallet support.
 - [ ] As a user, I want to transfer tokens using the Wallet with my hardware wallet-secured account, so I can move assets without using the CLI (@vgrichina unless we can do this in the Ledger app?) .
 - [ ] As a user, I want to add and remove keys from my hardware wallet secured-account, so I can use multiple devices, and create backup methods for my hardware wallet.
 - [ ] As a user, I want to view and interact with my hardware-wallet secured account in the Wallet, so I can learn more about my current asset balances and view recent activity.

**Comment by Patrick1904** [comment]
Closing as issue is outdated
