### ISSUE TITLE
Mainnet Wallet production checklist

### ISSUE THREAD

**Issue by vgrichina** [near/near-wallet#620]
### Overview

We need to prepare

### Checklist

- [x] Error reporting (using Sentry)
- [ ] Make sure all private data is scrubbed (ideally client-side) when reporting errors
- [ ] Use protected `stable` branch for deploy
- [ ] Make sure that deploy uses only plain Unix tools (i.e. JS bundle, etc should be part of the repo)
- [ ] Make sure JS bundle in repo is easily diffable between different `stable` releases (including dependency updates)
- [ ] CI needs to verify that bundle committed in repo matches what is built from source

**Comment by vgrichina** [comment]
@kcole16 @ilblackdragon wonder if I'm missing anything. Note that it's not supposed to be checklist of all stuff we need for mainnet support, etc.

This is just in terms of how we'll run production wallet in terms of deploy, code review, etc

**Comment by kcole16** [comment]
Think we should add the following either here or in another issue(s).

- [ ] Install Mixpanel via npm/or local copy
- [ ] Remove Google Analytics
